version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/backend/outputs
      - ./models:/app/models
    environment:
      - HF_ENDPOINT=https://hf-mirror.com

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
